### ISSUE TITLE
How to use ip-identity and header-identity filter together ?

### ISSUE THREAD

**Issue by vishal-kedia** [rackerlabs/repose#1280]
the usecase is one wants to rate limit the requests based on either ip or a particular header value which ever limit is breached first. I have tried different apporaches given below:

1. putting both the filter with same quality value and one rate limiting filter(headerlimit=50requests/min,iplimit=100requests/min): observation - only ip based filtering is happening.
2. putting higher quality value for the header-identity filter than ip-identity filter(headerlimit=100requests/min,iplimit=50requests/min): observation - only header based filtering is happening

in the above two apporaches the filter sequence was as below:
```
<filter name="ip-identity"/>
<filter name="header-identity"/>
<filter name="rate-limiting"/> 
```
and i have also tried with the above apporaches with the below sequence:
```
<filter name="header-identity"/>
<filter name="ip-identity"/>
<filter name="rate-limiting"/> 
```
3. putting both the filter with same quality value and two rate limiting filter (with below filter sequence): observation - which ever lesser limit is breached either header-identity or ip-identity, works as expected, but there is unnecessary addition of latency with the addition of rate limiting filter twice(with distributed database).
```
<filter name="header-identity"/>
<filter name="rate-limiting"/>
<filter name="ip-identity"/>
<filter name="rate-limiting"/>
```
so the question is what is the correct way of approaching the problem? To me it seem 1st apporach is logical and intuitive approach. plz correct if wrong.

**Comment by dmnjohns** [comment]
The way that the rate-limiting filter works is by using the highest quality "X-PP-User" header in the request to identify a user. If multiple values exist with the same quality for that header, the one to be used is technically indeterminate. Only one value of "X-PP-User" will be used by a single rate-limiting filter. Both the ip-identity and the header-identity filters will populate the "X-PP-User" header with a new value. This explains the behavior that you are currently seeing in your first two examples.

I'm actually somewhat surprised that your last solution works. Since the "X-PP-User" header is not removed, I would think that there's a chance the second rate-limiting filter would record another hit to the user identified by the value added by the header-identity filter.

The best solution I can come up with is to use two rate-limiting filters and setting the quality higher on the filter than comes later in the filter chain. That would look something like:
`<filter name="header-identity"/> 
<filter name="rate-limiting/>
<filter name="ip-identity"/> 
<filter name="rate-limiting"/>`

Note that, while having two rate-limiting filters will increase latency, a single instance of the distributed datastore will be shared between them. So the overhead will only be the memory cost of the second rate-limiting filter objects and time cost of the processing that the second rate-limiting filter performs.

Hopefully that helps, but let me know if there is anything that is still unclear. Also, the Repose project accepts feature requests and pull requests if there's functionality you want to added/altered!

**Comment by vishal-kedia** [comment]
thanks @dmnjohns for the detailed feedback, and sory for coming back late; you are right, actually I checked the configuration files for header identity and ip identity, and quality factor for ip identity was more than the header identity. And the solution that you suggested is exactly what i tried and thats how it was working. thanks again, i appreciate for the time you took to explain in such detail.
