### ISSUE TITLE
issue with url encoding of spaces

### ISSUE THREAD

**Issue by vishal-kedia** [rackerlabs/repose#1300]
As per http://www.w3schools.com/tags/ref_urlencode.asp, spaces in url can be replaces with '%20' or '+', Now if any request reaching repose has '%20' then repose decodes it and re-encodes it with '+', which is actually kind of changing the request in some way.

For Example - if client which is making the call creates a checksum of the encoded url and sends it as header for identifying the request tampering then in that case things may fail at the origin service coz the checksum it will make out of encoded url will be different than the one in the header

I know one can argue why create the checksum after encoding, why not before it, however i am not arguing over it. what my point is, that there can be systems which may be doing this, and if they want to use repose they can't, they will have to make changes in there code, and ideally introducing repose should not lead to such situations.

**Comment by wdschei** [comment]
You are correct that a current stock installation of Repose could not be configured in a manner to not break the specific use case you have defined.

However, as defined in [[RFC 2616 HTTP]](http://www.w3.org/TR/ct-guidelines/#ref-HTTP) [Section 1.3, Terminology](http://tools.ietf.org/html/rfc2616#section-1.3), Repose is not a **_transparent proxy_**, rather it is a **_non-transparent proxy_** since it provides added service. As such, the modification of the URI is a perfectly acceptable thing to occur. There are several other examples of this behavior within Repose as well. For example, all of the following could easily perform URI manipulation that would break your described scenario if configured to do so:

* [Translation filter](https://repose.atlassian.net/wiki/display/REPOSE/Translation+filter)
* [URI Normalization filter](https://repose.atlassian.net/wiki/display/REPOSE/URI+Normalization+filter)
* [URI Stripper filter](https://repose.atlassian.net/wiki/display/REPOSE/URI+Stripper+filter)

For this particular situation where the _origin service_ is requiring some part of the request from the original client to be unmodified or accounted for, the correct thing to do would be to add a pair of filters to the configured Repose stack. The first would be at the top of the stack and ensure the unmodified data is accurate (e.g. ensure the URI from the client was not tampered with by comparing it to the header data). The second would be towards the bottom of the stack and update the data to account for any modifications performed within Repose (e.g. modify the header appropriately after all possible transformations occur).

All that said, we are an open source project and welcome pull requests from everyone. So if you would like to create these filters and have them added to the baseline they would be more than appreciated.

**Comment by vishal-kedia** [comment]
thanks wdschei for such a detailed explanation, I feel you are right. However if we can look for the character used for encoding in the given input uri and use it for re-encoding later, wouldn't it be great ?
