### ISSUE TITLE
repose converts requests into chunked and breaks opestack apis running under httpd

### ISSUE THREAD

**Issue by chrisplo** [rackerlabs/repose#1355]
Keystone (and I believe other OpenStack APIs) do not support "Transfer-Encoding: chunked" when run under httpd:

https://git.openstack.org/cgit/openstack/keystone/commit/?id=05c01e26d1e62298489ba3894576faf3c352e2c9

Repose is converting non chunked requests into chunked requests, even with "pass-through" configuration.

If you try to turn off WSGIChunkedRequest in httpd configuration, you get a 411 response, indicating Content-Length needs to be set:
HTTP/1.1 411 Length Required

If you leave it on, python will error on read.

**Comment by chrisplo** [comment]
Found http-connection-pool.cfg.xml option to turn off chunking

Chunking seems to make sense for general purpose middleware, but for wrapping OpenStack, the defaults I found located below have issues:

repose/repose-aggregator/services/httpclient/impl/src/main/resources/META-INF/schema/config/http-connection-pool.xsd
<xs:attribute name="chunked-encoding" type="xs:boolean" use="optional" default="true">

https://repose.atlassian.net/wiki/display/REPOSE/HTTP+Connection+Pool+service

----------

Maybe treat as a documentation bug?

**Comment by wdschei** [comment]
The documentation referenced has been cleaned up a bit since this was originally opened. It is by no means where we would like the final documentation to be, but it is a great start. One key thing to remember is that even though a lot of OpenStack installations use Repose in front of many of the API's, that is not the only use case that we support.
