### ISSUE TITLE
 Filter has not yet initialized

### ISSUE THREAD

**Issue by vvsraju04** [rackerlabs/repose#1569]
While following the steps from [https://repose.atlassian.net/wiki/display/REPOSE/Quick+Setup](https://repose.atlassian.net/wiki/display/REPOSE/Quick+Setup) , getting following error in the logs : 

_Trans-Id:b85a8f7e-b789-406e-9eb3-900c9d38bbbc - 2016-07-17 17:40:06,451 1310341 [qtp130494156-40] ERROR org.openrepose.filters.headertranslation.HeaderTranslationFilter - Filter has not yet initialized... Please check your configuration files and your artifacts directory._

But i see header-translation artifacts : 
_$ find /var/repose -name header-translation*                                      
 /var/repose/09e7e933-eecb-4b41-a067-09dc24cac595/13bfb428-81ac-426f-a3fd-d9b9b3eaa769/lib/header-translation-filter-8.0.1.0.jar
/var/repose/67fe8017-70cd-47a6-a5fd-2ac77d378095/c1e8a301-0892-4e73-bb39-1fa6f959bf1c/lib/header-translation-filter-8.0.1.0.jar
/var/repose/7ddce673-b12d-4030-a245-2e0f9abecf6a/03d5c94f-61f4-4fe2-bed2-4c8d253b0b06/lib/header-translation-filter-8.0.1.0.jar
/var/repose/b15e2f65-9350-45c9-996c-8365dfe6369e/1ef5f309-f100-40b6-a9f5-7bbdc3301505/lib/header-translation-filter-8.0.1.0.jar
/var/repose/69b7c4fe-da8b-4ad8-a1f9-ac88a0496fea/6581cf90-85c3-4f80-b2d0-52d2d4e38af4/lib/header-translation-filter-8.0.1.0.jar
/var/repose/4bf09cbc-f6e9-4828-9900-d41bdc766173/f3f1f52a-5468-453c-aa87-9fd1122c107a/lib/header-translation-filter-8.0.1.0.jar
/var/repose/c32825f8-788a-4a7d-8b84-389fccb46e4e/9e816bc3-82c0-42d6-a87f-8b5f46895256/lib/header-translation-filter-8.0.1.0.jar_

**Comment by Mario-Lopez** [comment]
Hello.  While that error applies to configuration and artifact issues, it typically means there is a configuration error.  Since the Header Translation filter is reporting the error, it is likely in:
`/etc/repose/header-translation.cfg.xml`

Prior to that line in the log file, there should be another "ERROR" line giving you a better indication of what's wrong with the configuration file.  If you don't see that line, could you provide a Gist of the sanitized logs and your header-translation.cfg.xml file, please?

**Comment by vvsraju04** [comment]
Thank you @Mario-Lopez  . /etc/repose/header-translation.cfg.xml file was missing . I copied it from /etc/repose/examples and error is resolved .
