### ISSUE TITLE
Environment variables support in xml

### ISSUE THREAD

**Issue by ajays20078** [rackerlabs/repose#1715]
Is it possible to read environment variables while loading xml.

Ex:
Lets say XML has the below line
`<deployment-config http-port="${HTTP_PORT}">`

while loading the XML,read the environment variable HTTP_PORT and load the value for that. Certain frameworks support such type of env variables in config file. Is there support for this in repose?

**Comment by wdschei** [comment]
This is not something that is currently supported in Repose. However, we would like to learn more about your use case. Please email us directly at ReposeCore AT Rackspace.com and we will take a closer look into how we can support you.

**Comment by dmnjohns** [comment]
I can see value in using environment variables in configuration templates. More flexibility generally isn't a bad thing. That could get us closer to adhering to "12 Factor Application" standards and grant us some of those benefits, though I doubt we will drop configuration files in the near future. 

That being said, I believe most Repose users manage their Repose environments with a **C**onfiguration **M**anagment tool (e.g., Puppet). In that case, the **CM** tool should be able to handle variable substitution in the Repose configuration files. Depending on the tool, however, the values of the variables being substituted may originate from the host declaration file instead of environment variables. In the end, the result is similar, but the process to get there varies. 

As Bill said, we would love to hear more about your use case.

**Comment by ajays20078** [comment]
The use case arises when you dockerize the application and use a orchestration framework like mesos-marathon where  you have the flexibility of defining environment variable in the application payload, which also helps in keeping all the information in one place. 

A Configuration Management tool like Puppet/Chef is out of picture since these are dockerized application with pre-built docker images and this is where environment variables can be handy, although the other approach could be to mount the final substituted config directory into docker.

Also having this feature gives the flexibility to bake the config file in Docker image itself by marking only the variables which change across environments(staging/production) as ENV variables and exporting them during docker launch, whereas if you use the volume mount approach you will have to manage and maintain the entire config file apart from ensuring these files are avaliable across all mesos slaves for mounting, which can become a operational overhead.

Let me know if you need more information, i can share it over here or e-mail you folks directly.

**Comment by dmnjohns** [comment]
I think you hit the nail on the head with your explanation. I will note that we do actually publish a [Repose Docker image](https://hub.docker.com/r/rackerlabs/repose/) to DockerHub, and if you take a look at the Dockerfile, we mount the Repose configuration directory as a volume (assuming the user will mount their final configs). So the issues you have pointed out are present, but that's where we are at.

Anyway, this is great! We will definitely talk about this feature request and see what we can do.

**Comment by Mario-Lopez** [comment]
This feature will be added under this story:
https://repose.atlassian.net/browse/REP-5401
